`timescale 1ns / 1ps

module seu_eth_25g(
    input   wire                gt_rxp_in_0,
    input   wire                gt_rxp_in_1,
    input   wire                gt_rxp_in_2,
    input   wire                gt_rxp_in_3,
    input   wire                gt_rxn_in_0,
    input   wire                gt_rxn_in_1,
    input   wire                gt_rxn_in_2,
    input   wire                gt_rxn_in_3,
    output  wire                gt_txp_out_0,
    output  wire                gt_txp_out_1,
    output  wire                gt_txp_out_2,
    output  wire                gt_txp_out_3,
    output  wire                gt_txn_out_0,
    output  wire                gt_txn_out_1,
    output  wire                gt_txn_out_2,
    output  wire                gt_txn_out_3,
    input   wire                sys_reset,
    input   wire                dclk,               //128M
    input   wire                gt_refclk_p,        //156.25M
    input   wire                gt_refclk_n,
    output  wire                eth_clk_0,
    output  wire                eth_clk_1,
    output  wire                eth_clk_2,
    output  wire                eth_clk_3,
    output  wire                eth_reset_0,
    output  wire                eth_reset_1,
    output  wire                eth_reset_2,
    output  wire                eth_reset_3,
    output  wire                gt_refclk_out,
    input   wire    [63 : 0]    eth_d_0,
    input   wire    [63 : 0]    eth_d_1,
    input   wire    [63 : 0]    eth_d_2,
    input   wire    [63 : 0]    eth_d_3,
    input   wire    [7 : 0]     eth_c_0,
    input   wire    [7 : 0]     eth_c_1,
    input   wire    [7 : 0]     eth_c_2,
    input   wire    [7 : 0]     eth_c_3
    );

wire rx_clk_out_0;
wire rx_clk_out_1;
wire rx_clk_out_2;
wire rx_clk_out_3;

xxv_ethernet u_xxv_ethernet(
  .gt_rxp_in_0(gt_rxp_in_0),                                                  
  .gt_rxp_in_1(gt_rxp_in_1),                                                  
  .gt_rxp_in_2(gt_rxp_in_2),                                                  
  .gt_rxp_in_3(gt_rxp_in_3),                                                  
  .gt_rxn_in_0(gt_rxn_in_0),                                                  
  .gt_rxn_in_1(gt_rxn_in_1),                                                  
  .gt_rxn_in_2(gt_rxn_in_2),                                                  
  .gt_rxn_in_3(gt_rxn_in_3),                                                  
  .gt_txp_out_0(gt_txp_out_0),                                                
  .gt_txp_out_1(gt_txp_out_1),                                                
  .gt_txp_out_2(gt_txp_out_2),                                                
  .gt_txp_out_3(gt_txp_out_3),                                                
  .gt_txn_out_0(gt_txn_out_0),                                                
  .gt_txn_out_1(gt_txn_out_1),                                                
  .gt_txn_out_2(gt_txn_out_2),                                                
  .gt_txn_out_3(gt_txn_out_3),                                                
  .rx_core_clk_0(rx_clk_out_0),                                              
  .rx_core_clk_1(rx_clk_out_1),                                              
  .rx_core_clk_2(rx_clk_out_2),                                              
  .rx_core_clk_3(rx_clk_out_3),                                              
  .txoutclksel_in_0(3'd5),                                        
  .rxoutclksel_in_0(3'd5),                                        
  .txoutclksel_in_1(3'd5),                                        
  .rxoutclksel_in_1(3'd5),                                        
  .txoutclksel_in_2(3'd5),                                        
  .rxoutclksel_in_2(3'd5),                                        
  .txoutclksel_in_3(3'd5),                                        
  .rxoutclksel_in_3(3'd5),                                        
  .gtwiz_reset_tx_datapath_0(0),                      
  .gtwiz_reset_tx_datapath_1(0),                      
  .gtwiz_reset_tx_datapath_2(0),                      
  .gtwiz_reset_tx_datapath_3(0),                      
  .gtwiz_reset_rx_datapath_0(0),                      
  .gtwiz_reset_rx_datapath_1(0),                      
  .gtwiz_reset_rx_datapath_2(0),                      
  .gtwiz_reset_rx_datapath_3(0),                      
  .rxrecclkout_0(),                                              
  .rxrecclkout_1(),                                              
  .rxrecclkout_2(),                                              
  .rxrecclkout_3(),                                              
  .sys_reset(sys_reset),                                                      
  .dclk(dclk),                                                                
  .tx_mii_clk_0(eth_clk_0),                                                
  .tx_mii_clk_1(eth_clk_1),                                                
  .tx_mii_clk_2(eth_clk_2),                                                
  .tx_mii_clk_3(eth_clk_3),                                                
  .rx_clk_out_0(rx_clk_out_0),                                              
  .rx_clk_out_1(rx_clk_out_1),                                              
  .rx_clk_out_2(rx_clk_out_2),                                              
  .rx_clk_out_3(rx_clk_out_3),                                              
  .gt_refclk_p(gt_refclk_p),                                                  
  .gt_refclk_n(gt_refclk_n),                                                  
  .gt_refclk_out(gt_refclk_out),                                             
  .gtpowergood_out_0(),                                      
  .gtpowergood_out_1(),                                      
  .gtpowergood_out_2(),                                      
  .gtpowergood_out_3(),                                      
  .rx_reset_0(0),                                                    
  .rx_reset_1(0),                                                    
  .rx_reset_2(0),                                                    
  .rx_reset_3(0),                                                    
  .user_rx_reset_0(),                                          
  .user_rx_reset_1(),                                          
  .user_rx_reset_2(),                                          
  .user_rx_reset_3(),                                          
  .rx_mii_d_0(),                                                    
  .rx_mii_d_1(),                                                    
  .rx_mii_d_2(),                                                    
  .rx_mii_d_3(),                                                    
  .rx_mii_c_0(),                                                    
  .rx_mii_c_1(),                                                    
  .rx_mii_c_2(),                                                    
  .rx_mii_c_3(),                                                    
  .ctl_rx_test_pattern_0(0),                              
  .ctl_rx_test_pattern_1(0),                              
  .ctl_rx_test_pattern_2(0),                              
  .ctl_rx_test_pattern_3(0),                              
  .ctl_rx_data_pattern_select_0(0),                
  .ctl_rx_data_pattern_select_1(0),                
  .ctl_rx_data_pattern_select_2(0),                
  .ctl_rx_data_pattern_select_3(0),                
  .ctl_rx_test_pattern_enable_0(0),                
  .ctl_rx_test_pattern_enable_1(0),                
  .ctl_rx_test_pattern_enable_2(0),                
  .ctl_rx_test_pattern_enable_3(0),                
  .ctl_rx_prbs31_test_pattern_enable_0(0),  
  .ctl_rx_prbs31_test_pattern_enable_1(0),  
  .ctl_rx_prbs31_test_pattern_enable_2(0),  
  .ctl_rx_prbs31_test_pattern_enable_3(0),  
  .stat_rx_framing_err_0(),                        
  .stat_rx_framing_err_1(),                        
  .stat_rx_framing_err_2(),                        
  .stat_rx_framing_err_3(),                        
  .stat_rx_framing_err_valid_0(),                  
  .stat_rx_framing_err_valid_1(),                  
  .stat_rx_framing_err_valid_2(),                  
  .stat_rx_framing_err_valid_3(),                  
  .stat_rx_local_fault_0(),                        
  .stat_rx_local_fault_1(),                        
  .stat_rx_local_fault_2(),                        
  .stat_rx_local_fault_3(),                        
  .stat_rx_block_lock_0(),                         
  .stat_rx_block_lock_1(),                         
  .stat_rx_block_lock_2(),                         
  .stat_rx_block_lock_3(),                         
  .stat_rx_valid_ctrl_code_0(),                    
  .stat_rx_valid_ctrl_code_1(),                    
  .stat_rx_valid_ctrl_code_2(),                    
  .stat_rx_valid_ctrl_code_3(),                    
  .stat_rx_status_0(),                             
  .stat_rx_status_1(),                             
  .stat_rx_status_2(),                             
  .stat_rx_status_3(),                             
  .stat_rx_hi_ber_0(),                             
  .stat_rx_hi_ber_1(),                             
  .stat_rx_hi_ber_2(),                             
  .stat_rx_hi_ber_3(),                             
  .stat_rx_bad_code_0(),                           
  .stat_rx_bad_code_1(),                           
  .stat_rx_bad_code_2(),                           
  .stat_rx_bad_code_3(),                           
  .stat_rx_bad_code_valid_0(),                     
  .stat_rx_bad_code_valid_1(),                     
  .stat_rx_bad_code_valid_2(),                     
  .stat_rx_bad_code_valid_3(),                     
  .stat_rx_error_0(),                            
  .stat_rx_error_1(),                            
  .stat_rx_error_2(),                            
  .stat_rx_error_3(),                            
  .stat_rx_error_valid_0(),                        
  .stat_rx_error_valid_1(),                        
  .stat_rx_error_valid_2(),                        
  .stat_rx_error_valid_3(),                        
  .stat_rx_fifo_error_0(),                         
  .stat_rx_fifo_error_1(),                         
  .stat_rx_fifo_error_2(),                         
  .stat_rx_fifo_error_3(),                         
  .tx_reset_0(0),                                                    
  .tx_reset_1(0),                                                    
  .tx_reset_2(0),                                                    
  .tx_reset_3(0),                                                    
  .user_tx_reset_0(eth_reset_0),                                          
  .user_tx_reset_1(eth_reset_1),                                          
  .user_tx_reset_2(eth_reset_2),                                          
  .user_tx_reset_3(eth_reset_3),                                          
  .tx_mii_d_0(eth_d_0),                                                    
  .tx_mii_d_1(eth_d_1),                                                    
  .tx_mii_d_2(eth_d_2),                                                    
  .tx_mii_d_3(eth_d_3),                                                    
  .tx_mii_c_0(eth_c_0),                                                    
  .tx_mii_c_1(eth_c_1),                                                    
  .tx_mii_c_2(eth_c_2),                                                    
  .tx_mii_c_3(eth_c_3),                                                    
  .stat_tx_local_fault_0(),                              
  .stat_tx_local_fault_1(),                              
  .stat_tx_local_fault_2(),                              
  .stat_tx_local_fault_3(),                              
  .ctl_tx_test_pattern_0(0),                 
  .ctl_tx_test_pattern_1(0),                 
  .ctl_tx_test_pattern_2(0),                 
  .ctl_tx_test_pattern_3(0),                 
  .ctl_tx_test_pattern_enable_0(0),          
  .ctl_tx_test_pattern_enable_1(0),          
  .ctl_tx_test_pattern_enable_2(0),          
  .ctl_tx_test_pattern_enable_3(0),          
  .ctl_tx_test_pattern_select_0(0),          
  .ctl_tx_test_pattern_select_1(0),          
  .ctl_tx_test_pattern_select_2(0),          
  .ctl_tx_test_pattern_select_3(0),          
  .ctl_tx_data_pattern_select_0(0),          
  .ctl_tx_data_pattern_select_1(0),          
  .ctl_tx_data_pattern_select_2(0),          
  .ctl_tx_data_pattern_select_3(0),          
  .ctl_tx_test_pattern_seed_a_0(58'd0),                
  .ctl_tx_test_pattern_seed_a_1(58'd0),                
  .ctl_tx_test_pattern_seed_a_2(58'd0),                
  .ctl_tx_test_pattern_seed_a_3(58'd0),                
  .ctl_tx_test_pattern_seed_b_0(58'd0),                
  .ctl_tx_test_pattern_seed_b_1(58'd0),                
  .ctl_tx_test_pattern_seed_b_2(58'd0),                
  .ctl_tx_test_pattern_seed_b_3(58'd0),                
  .ctl_tx_prbs31_test_pattern_enable_0(0), 
  .ctl_tx_prbs31_test_pattern_enable_1(0), 
  .ctl_tx_prbs31_test_pattern_enable_2(0), 
  .ctl_tx_prbs31_test_pattern_enable_3(0), 
  .gt_loopback_in_0(3'd0),                                        
  .gt_loopback_in_1(3'd0),                                        
  .gt_loopback_in_2(3'd0),                                        
  .gt_loopback_in_3(3'd0),                                        
  .qpllreset_in_0(0)                               
);

endmodule

